### ISSUE TITLE
Building breaks on Python 2.7

### ISSUE THREAD

**Issue by MinchinWeb** [MinchinWeb/minchin.pelican.plugins.cname#3]
```
3:20:49 PM: Collecting minchin.pelican.plugins.cname==1.0.4 (from -r requirements.txt (line 20))
3:20:49 PM:   Downloading minchin.pelican.plugins.cname-1.0.4.tar.gz
3:20:49 PM:     Complete output from command python setup.py egg_info:
3:20:49 PM:     Traceback (most recent call last):
3:20:49 PM:       File "<string>", line 1, in <module>
3:20:49 PM:       File "/tmp/pip-build-J0bmVJ/minchin.pelican.plugins.cname/setup.py", line 21, in <module>
3:20:49 PM:         version=get_version(),
3:20:49 PM:       File "/tmp/pip-build-J0bmVJ/minchin.pelican.plugins.cname/setup.py", line 13, in get_version
3:20:49 PM:         with open(os.path.join(base_dir, filename), encoding="utf-8") as initfile:
3:20:49 PM:     TypeError: 'encoding' is an invalid keyword argument for this function
3:20:49 PM:     ----------------------------------------
3:20:49 PM: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-J0bmVJ/minchin.pelican.plugins.cname/
```

**Comment by MinchinWeb** [comment]
I'm not going to try and support Python 2 any more.
